name = "vless-speed-demon"
main = "_worker.js"
compatibility_date = "2024-09-13"
compatibility_flags = [ "nodejs_compat" ]

[vars]
# သင့်ရဲ့ UUID ကို ထည့်ပါ (Secret Dashboard ဝင်ဖို့အတွက်ပါ သုံးပါမယ်)
#UUID = ""
PROXY_URL = "https://galaxytunnel.github.io/PROXYIP.txt"
# WebSocket ချိတ်ဆက်ရန် လျှို့ဝှက် Path
WS_PATH = "/speed-tunnel"

# ပိတ်ဆို့ခံရသော Website များအတွက် အရန် Proxy IP
PROXYIP = ["104.16.85.20",
"104.17.123.45",
"104.21.234.45",
"172.64.155.1",
"172.65.250.1"]
