name = "vless-speed-demon"
main = "_worker.js"
compatibility_date = "2024-09-13"
compatibility_flags = [ "nodejs_compat" ]

[vars]
# သင့်ရဲ့ UUID ကို ထည့်ပါ (Secret Dashboard ဝင်ဖို့အတွက်ပါ သုံးပါမယ်)
#UUID = ""

# WebSocket ချိတ်ဆက်ရန် လျှို့ဝှက် Path
WS_PATH = "/speed-tunnel"

# ပိတ်ဆို့ခံရသော Website များအတွက် အရန် Proxy IP
PROXY_IP = "cdn-b100.xn--b6gac.eu.org"
